sudo: false

language: go

go_import_path: github.com/imperfectgo/go-strftime

go:
  - '1.7.x'
  - '1.8.x'
  - '1.9.x'
  - '1.10.x'
  - master

matrix:
  # It's ok if our code fails on unstable development versions of Go.
  allow_failures:
    - go: master
  # Don't wait for tip tests to finish. Mark the test run green if the
  # tests pass on the stable versions of Go.
  fast_finish: true

notifications:
  email: false

install:
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls

script:
  - overalls -project=github.com/imperfectgo/go-strftime -covermode=atomic -- -race

after_script:
  - mv overalls.coverprofile coverage.txt
  - bash <(curl -s https://codecov.io/bash)
